# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b2f3efe4b86d9d1944f237f8d33a78690b4445f1b06d1eb7318ae8e397872bfc82e4f8b7d26d81a88ea3258bce48495927703dbeee4e28972672e47b2bfec57f

test:
  secret_key_base: 0dc721bf66ab47a2424468946e705d3a2e66bf4b8cbc3c20e4d97e20341ae7996ee1229caab4faad14c78c06119f1cd233034577b1190107ee5cf8f6ac1dc015

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
